// AUTO-GENERATED by scripts/sync-icons.mjs — do not hand-edit.
export const STOCK_ICONS: ReadonlySet<string> = new Set(["AAOI","AAPL","AMAT","AMD","AMZN","ARM","ASML","AVGO","BABA","BB","BE","BIRD","BX","COIN","COST","CRM","CRWD","DELL","DKNG","EBAY","GEV","GME","GOOGL","HIMS","HOOD","IBM","INTC","IREN","LITE","LLY","META","MRNA","MRVL","MSFT","MSTR","MU","NBIS","NET","NFLX","NOK","NOW","NVDA","ORCL","PLTR","QCOM","RDDT","RIVN","RKLB","TSLA","TSM","WDC","ZM"]);
export const FOREX_ICONS: ReadonlySet<string> = new Set(["EUR","GBP","JPY"]);
export const COMMODITY_ICONS: ReadonlySet<string> = new Set(["CL","CO","GOLD","USO","WTI"]);
