/**
 * Sync market icons from the cloned NVSTly icons repo into app/public.
 * Copies only symbols in our universe (not all 5,668 files) and writes
 * app/src/lib/iconManifest.ts so the UI knows what exists (no flicker).
 * Re-run when new HIP-3 markets appear: node scripts/sync-icons.mjs
 */
import { copyFileSync, mkdirSync, existsSync, statSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = join(root, 'icons')
const PUB = join(root, 'app', 'public', 'icons')

// Full xyz HIP-3 roster (stocks/ETFs) + extras. Missing files -> badge fallback.
const STOCKS = [
  'AAOI', 'AAPL', 'AMAT', 'AMD', 'AMZN', 'ARM', 'ASML', 'AVGO', 'BABA', 'BB',
  'BE', 'BIRD', 'BOT', 'BX', 'CBRS', 'COIN', 'COST', 'CRCL', 'CRWD', 'CRWV',
  'CXMT', 'DELL', 'DKNG', 'DRAM', 'EBAY', 'EWJ', 'EWT', 'EWY', 'EWZ', 'GEV',
  'GIGADEV', 'GME', 'GOOGL', 'HIMS', 'HOOD', 'HYUNDAI', 'IBM', 'INTC', 'IREN',
  'KIOXIA', 'KORU', 'KR200', 'LITE', 'LLY', 'LYTE', 'MAGS', 'META', 'MINIMAX',
  'MRNA', 'MRVL', 'MSFT', 'MSTR', 'MU', 'NBIS', 'NCLD', 'NET', 'NFLX', 'NOK',
  'NOW', 'NVDA', 'ORCL', 'PLTR', 'PURRDAT', 'QCOM', 'QNT', 'RDDT', 'RIVN',
  'RKLB', 'SHAZ', 'SHEIN', 'SKHX', 'SKHY', 'SMH', 'SMSN', 'SNDK', 'SOFTBANK',
  'SOXL', 'SPCX', 'STRC', 'TSLA', 'TSM', 'UNITREE', 'URNM', 'USAR', 'WDC',
  'XBI', 'XLE', 'ZHIPU', 'ZM', 'CRM', 'AMD',
]
const FOREX = ['EUR', 'GBP', 'JPY']
// Commodities with ticker-style logos in the repo. Rest -> badge.
const COMMODITIES = ['GOLD', 'WTI', 'USO', 'CL', 'CO']

function sync(list, srcDir, outDir) {
  mkdirSync(outDir, { recursive: true })
  const found = []
  const missing = []
  let bytes = 0
  for (const sym of new Set(list)) {
    const src = join(SRC, srcDir, `${sym}.png`)
    if (existsSync(src)) {
      copyFileSync(src, join(outDir, `${sym}.png`))
      bytes += statSync(src).size
      found.push(sym)
    } else {
      missing.push(sym)
    }
  }
  return { found, missing, bytes }
}

const s = sync(STOCKS, 'ticker_icons', join(PUB, 'stocks'))
const f = sync(FOREX, 'forex_icons', join(PUB, 'forex'))
const c = sync(COMMODITIES, 'ticker_icons', join(PUB, 'commodities'))

const manifest =
  `// AUTO-GENERATED by scripts/sync-icons.mjs — do not hand-edit.\n` +
  `export const STOCK_ICONS: ReadonlySet<string> = new Set(${JSON.stringify(s.found.sort())});\n` +
  `export const FOREX_ICONS: ReadonlySet<string> = new Set(${JSON.stringify(f.found.sort())});\n` +
  `export const COMMODITY_ICONS: ReadonlySet<string> = new Set(${JSON.stringify(c.found.sort())});\n`
const out = join(root, 'app', 'src', 'lib', 'iconManifest.ts')
const { writeFileSync } = await import('node:fs')
writeFileSync(out, manifest)

const kb = (n) => `${(n / 1024).toFixed(0)}KB`
console.log(`stocks: ${s.found.length} copied (${kb(s.bytes)}), missing: ${s.missing.join(', ') || 'none'}`)
console.log(`forex: ${f.found.length} copied, missing: ${f.missing.join(', ') || 'none'}`)
console.log(`commodities: ${c.found.length} copied (${c.found.join(', ')}), badge fallback: ${c.missing.join(', ') || 'none'}`)
console.log(`manifest -> ${out}`)
